name: Validate

on: [push]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # QEMU is needed to build for arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compile source
        run:  python -m compileall src

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: false
          tags: user/app:latest